"""initial schema

Revision ID: 1d9f18071173
Revises: 
Create Date: 2026-02-15 20:14:23.835076
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1d9f18071173'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=True),
    sa.Column('patient_phone', sa.String(length=500), nullable=True),
    sa.Column('insurance_company', sa.String(length=255), nullable=False),
    sa.Column('insurance_phone', sa.String(length=50), nullable=True),
    sa.Column('policy_number', sa.String(length=500), nullable=True),
    sa.Column('group_number', sa.String(length=255), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('provider_npi', sa.String(length=20), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('cpt_codes', sa.JSON(), nullable=True),
    sa.Column('charge_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING_ESTIMATE', 'ESTIMATE_GENERATED', 'CLAIM_SUBMITTED', 'CALLING_INSURER', 'AWAITING_PAYMENT', 'RESOLVED', name='ticketstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('call_sid', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RINGING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'NO_ANSWER', 'VOICEMAIL', name='callstatus'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reference_numbers', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('current_state', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('charge_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reimbursement_low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reimbursement_high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('oop_low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('oop_high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benefits_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('call_log_id', sa.Uuid(), nullable=True),
    sa.Column('deductible_individual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deductible_met', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('oop_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coinsurance_percentage', sa.Integer(), nullable=True),
    sa.Column('reimbursement_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benefits_data')
    op.drop_table('file_uploads')
    op.drop_table('estimates')
    op.drop_table('call_logs')
    op.drop_table('tickets')
    # ### end Alembic commands ###
