"""add call log fields

Revision ID: 9799b830c6b1
Revises: e56d6310259b
Create Date: 2026-02-15 20:59:45.772048
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9799b830c6b1'
down_revision: Union[str, None] = 'e56d6310259b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('rep_name', sa.String(length=255), nullable=True))
    op.add_column('call_logs', sa.Column('reference_number', sa.String(length=255), nullable=True))
    op.add_column('call_logs', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('call_logs', sa.Column('call_outcome', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'call_outcome')
    op.drop_column('call_logs', 'admin_notes')
    op.drop_column('call_logs', 'reference_number')
    op.drop_column('call_logs', 'rep_name')
    # ### end Alembic commands ###
