"""add insurance carriers

Revision ID: e56d6310259b
Revises: 1d9f18071173
Create Date: 2026-02-15 20:31:19.165518
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e56d6310259b'
down_revision: Union[str, None] = '1d9f18071173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_carriers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('carrier_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('phone_numbers', sa.JSON(), nullable=True),
    sa.Column('ivr_navigation', sa.JSON(), nullable=True),
    sa.Column('required_info', sa.JSON(), nullable=True),
    sa.Column('avg_hold_time_minutes', sa.Integer(), nullable=True),
    sa.Column('reference_number_format', sa.String(length=255), nullable=True),
    sa.Column('common_questions', sa.JSON(), nullable=True),
    sa.Column('reimbursement_methods', sa.JSON(), nullable=True),
    sa.Column('script_notes', sa.Text(), nullable=True),
    sa.Column('special_considerations', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_key')
    )
    op.add_column('tickets', sa.Column('carrier_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'insurance_carriers', ['carrier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'carrier_id')
    op.drop_table('insurance_carriers')
    # ### end Alembic commands ###
